"""Messaging layer: typed events, subject helpers and the bus abstraction."""

from __future__ import annotations

from .bus import InMemoryBus, MessageBus, Subscription, subject_matches
from .events import (
    AbortMission,
    AssignMission,
    DroneOffline,
    DroneRegistered,
    Event,
    EventType,
    FaultDetected,
    Heartbeat,
    IncidentCreated,
    MissionAccepted,
    MissionAssigned,
    MissionCompleted,
    MissionCreated,
    MissionFailed,
    MissionProgress,
    MissionReassigned,
    Ping,
    ReturnToBase,
    Telemetry,
    VisionEvent,
)
from .topics import (
    ALL_TELEMETRY,
    ALL_UPLINK_EVENTS,
    FLEET_EVENT,
    command_subject,
    telemetry_subject,
    uplink_event_subject,
)

__all__ = [
    "ALL_TELEMETRY",
    "ALL_UPLINK_EVENTS",
    "FLEET_EVENT",
    "AbortMission",
    "AssignMission",
    "DroneOffline",
    "DroneRegistered",
    "Event",
    "EventType",
    "FaultDetected",
    "Heartbeat",
    "InMemoryBus",
    "IncidentCreated",
    "MessageBus",
    "MissionAccepted",
    "MissionAssigned",
    "MissionCompleted",
    "MissionCreated",
    "MissionFailed",
    "MissionProgress",
    "MissionReassigned",
    "Ping",
    "ReturnToBase",
    "Subscription",
    "Telemetry",
    "VisionEvent",
    "command_subject",
    "subject_matches",
    "telemetry_subject",
    "uplink_event_subject",
]
